{% set name = "llama-parse" %}
{% set version = "0.6.94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_parse-{{ version }}.tar.gz
  sha256: d9e4347ec6caa1e9d5266cc5d4d8b29a29aa0d0948d921a26c73d3e4aaf5ba72

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - llama-cloud-services >=0.6.94
    - llama-index-core >=0.11.0
    - pydantic !=2.10
    - click >=8.1.7,<9.0.0

test:
  imports:
    - llama_parse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/run-llama/llama_parse
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Parse files into RAG-Optimized formats.
  description: |
    LlamaParse is a GenAI-native document parser that can parse complex document
    data for any downstream LLM use case (RAG, agents). It supports multiple file
    types including .pdf, .pptx, .docx, .xlsx, and .html with table recognition
    and multimodal parsing and chunking capabilities.
  doc_url: https://docs.cloud.llamaindex.ai/
  dev_url: https://github.com/run-llama/llama_parse

extra:
  recipe-maintainers:
    - AnacondaRecipes/support
