{% set name = "llama-parse" %}
{% set version = "0.6.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_parse-{{ version }}.tar.gz
  sha256: c707b31152155c9bae84e316fab790bbc8c85f4d8825ce5ee386ebeb7db258f1

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - llama-cloud-services >=0.6.54

test:
  imports:
    - llama_parse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/run-llama/llama_parse
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Parse files into RAG-Optimized formats.
  description: |
    LlamaParse is a GenAI-native document parser that can parse complex document
    data for any downstream LLM use case (RAG, agents). It supports multiple file
    types including .pdf, .pptx, .docx, .xlsx, and .html with table recognition
    and multimodal parsing and chunking capabilities.
  doc_url: https://docs.cloud.llamaindex.ai/
  dev_url: https://github.com/run-llama/llama_parse

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
